package rmhub.mod.weatherstation.constant;

import java.util.Arrays;
import java.util.List;

public interface AlertRuleCode {

  String ALR_WIND_LEVEL1 = "ALR_WIND_LEVEL1";
  String ALR_WIND_LEVEL2 = "ALR_WIND_LEVEL2";
  String ALR_ES_LVL1_WET_TRANSITIONAL = "ALR_ES_LVL1_WET_TRANSITIONAL";
  String ALR_ES_LVL2_HUMID = "ALR_ES_LVL2_HUMID";
  String ALR_ES_LVL3_WET = "ALR_ES_LVL3_WET";
  String ALR_ES_LVL4_STREAMING_RAIN = "ALR_ES_LVL4_STREAMING_RAIN";
  String ALR_ES_LVL5_WHITE_FROZEN = "ALR_ES_LVL5_WHITE_FROZEN";
  String ALR_ES_LVL6_FROSTY = "ALR_ES_LVL6_FROSTY";
  String ALR_ES_LVL7_ICY = "ALR_ES_LVL7_ICY";
  String ALR_ES_LVL8_SLEET = "ALR_ES_LVL8_SLEET";
  String ALR_ES_LVL9_HAILED = "ALR_ES_LVL9_HAILED";
  String ALR_ES_LVL10_FRESH_SNOW = "ALR_ES_LVL10_FRESH_SNOW";
  String ALR_ES_LVL11_MELTING_SNOW = "ALR_ES_LVL11_MELTING_SNOW";
  String ALR_ES_LVL12_PACKED_SNOW = "ALR_ES_LVL12_PACKED_SNOW";
  String ALR_ES_LVL13_ICE_FROZEN = "ALR_ES_LVL13_ICE_FROZEN";
  String ALR_ES_LVL14_FROZEN_SNOW = "ALR_ES_LVL14_FROZEN_SNOW";
  String ALR_ES_LVL15_GRANULAR_SNOW = "ALR_ES_LVL15_GRANULAR_SNOW";
  String ALR_ES_LVL16_SNOWDRIFTS = "ALR_ES_LVL16_SNOWDRIFTS";

  List<String> lsAlertCode = Arrays
      .asList(ALR_WIND_LEVEL1, ALR_WIND_LEVEL2, ALR_ES_LVL1_WET_TRANSITIONAL, ALR_ES_LVL2_HUMID, ALR_ES_LVL3_WET,
          ALR_ES_LVL4_STREAMING_RAIN, ALR_ES_LVL5_WHITE_FROZEN, ALR_ES_LVL6_FROSTY, ALR_ES_LVL7_ICY, ALR_ES_LVL8_SLEET, ALR_ES_LVL9_HAILED,
          ALR_ES_LVL10_FRESH_SNOW,
          ALR_ES_LVL11_MELTING_SNOW, ALR_ES_LVL12_PACKED_SNOW, ALR_ES_LVL13_ICE_FROZEN, ALR_ES_LVL14_FROZEN_SNOW,
          ALR_ES_LVL15_GRANULAR_SNOW, ALR_ES_LVL16_SNOWDRIFTS);

  String ALR_WIND_SEARCH = "ALR_WIND";
  String ALR_SURFACE_SEARCH = "ALR_ES";
}
