apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafdrop.serviceName }}
  labels:
    run: {{ .Values.kafdrop.serviceName }}
spec:
  ports:
    - port: {{ .Values.kafdrop.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.kafdrop.serviceName }}
