apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.serviceName }}
  labels:
    run: {{ .Values.kafka.serviceName }}
spec:
  ports:
  - port:  {{ .Values.kafka.port }}
    protocol: TCP
    targetPort: service-port
  clusterIP: None
  selector:
    app: {{ .Values.kafka.serviceName }}
