apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.serviceName }}
  labels:
    run: {{ .Values.pgadmin.serviceName }}
spec:
  ports:
  - port: {{ .Values.pgadmin.port }}
    targetPort: pgadmin-port
    protocol: TCP 
  selector:
    app: {{ .Values.pgadmin.serviceName }} 