# Global configuration
global:
  scrape_interval: '30s'
  scrape_timeout: '5s'
  external_labels:
    namespace: 'rmhub'

# A list of scrape configurations
scrape_configs:

  - job_name: 'traffic-logger-module'
    scheme: 'http'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['traffic-logger-module:8165']
    # bearer_token_file: './vms-connector-metrics-token'
